# 베이스 이미지
FROM python:3.10-slim

#작업 폴더 설정
WORKDIR /opt/myproject

RUN apt -y update

RUN apt -y upgrade

#chrome driver에 필요한 라이브러리 설치
RUN apt install -y libglib2.0-0 libnss3 libx11-xcb1 libxcb1 libnspr4 libnss3 apt-utils wget

#chrome 설치
RUN wget -q https://mirror.cs.uchicago.edu/google-chrome/pool/main/g/google-chrome-stable/google-chrome-stable_119.0.6045.199-1_amd64.deb
RUN apt install -y ./google-chrome-stable_119.0.6045.199-1_amd64.deb

# ./google-chrome-stable_119.0.6045.199-1_amd64.deb 삭제
RUN rm google-chrome-stable_119.0.6045.199-1_amd64.deb

CMD ["bash"]