# 베이스 이미지
FROM silgerae_base

# TZ=Asia/Seoul 설정
ENV TZ=Asia/Seoul

#작업 폴더 설정
WORKDIR /opt/myproject

# 의존성 설치
RUN pip3 install --upgrade pip

# 소스코드 복사
COPY . /opt/myproject

RUN pip3 install -r requirements.txt

# 실행 파일 설정
CMD ["python3","app.py"]